spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: FalaqNashr#
  application:
    name: book-shop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: MySuperSecretKeyThatIsAtLeast32CharactersLong
  expire_time:
    604800000

    #  url: jdbc:postgresql://localhost:5432/postgres
    # username: postgres
    # password: FalaqNashr#
